// <auto-generated />
using System;
using Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Datos.Migrations
{
    [DbContext(typeof(ProyectoContext))]
    [Migration("20211125230457_M1")]
    partial class M1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entidad.Persona", b =>
                {
                    b.Property<string>("identificacion")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoIdentificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("identificacion");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("Entidad.Peticion", b =>
                {
                    b.Property<int>("codigoPeticion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("contexto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaPeticion")
                        .HasColumnType("datetime2");

                    b.Property<string>("funcionarioEncargadouserName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("referenciaFuncionario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("referenciaSolicitante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("solicitanteESTuserName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("codigoPeticion");

                    b.HasIndex("funcionarioEncargadouserName");

                    b.HasIndex("solicitanteESTuserName");

                    b.ToTable("Peticiones");
                });

            modelBuilder.Entity("Entidad.Proyecto", b =>
                {
                    b.Property<int>("codigoProyecto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("areaProyecto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("comentariosProyecto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estadoProyecto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("evaluadorProyecto1userName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("evaluadorProyecto2userName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("fechaPresentacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("grupoDeInvestigacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("investigadorPrincipaluserName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("investigadorSecundariouserName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("lineaDeInvestigacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("linkProyecto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("referenciaEvaluadorProyecto1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("referenciaEvaluadorProyecto2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("referenciaInvestigadorPrincipal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("referenciaInvestigadorSecundario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoProyecto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tituloProyecto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codigoProyecto");

                    b.HasIndex("evaluadorProyecto1userName");

                    b.HasIndex("evaluadorProyecto2userName");

                    b.HasIndex("investigadorPrincipaluserName");

                    b.HasIndex("investigadorSecundariouserName");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("Entidad.Usuario", b =>
                {
                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("personaidentificacion")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("userType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userName");

                    b.HasIndex("personaidentificacion");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Entidad.Peticion", b =>
                {
                    b.HasOne("Entidad.Usuario", "funcionarioEncargado")
                        .WithMany()
                        .HasForeignKey("funcionarioEncargadouserName");

                    b.HasOne("Entidad.Usuario", "solicitanteEST")
                        .WithMany()
                        .HasForeignKey("solicitanteESTuserName");

                    b.Navigation("funcionarioEncargado");

                    b.Navigation("solicitanteEST");
                });

            modelBuilder.Entity("Entidad.Proyecto", b =>
                {
                    b.HasOne("Entidad.Usuario", "evaluadorProyecto1")
                        .WithMany()
                        .HasForeignKey("evaluadorProyecto1userName");

                    b.HasOne("Entidad.Usuario", "evaluadorProyecto2")
                        .WithMany()
                        .HasForeignKey("evaluadorProyecto2userName");

                    b.HasOne("Entidad.Usuario", "investigadorPrincipal")
                        .WithMany()
                        .HasForeignKey("investigadorPrincipaluserName");

                    b.HasOne("Entidad.Usuario", "investigadorSecundario")
                        .WithMany()
                        .HasForeignKey("investigadorSecundariouserName");

                    b.Navigation("evaluadorProyecto1");

                    b.Navigation("evaluadorProyecto2");

                    b.Navigation("investigadorPrincipal");

                    b.Navigation("investigadorSecundario");
                });

            modelBuilder.Entity("Entidad.Usuario", b =>
                {
                    b.HasOne("Entidad.Persona", "persona")
                        .WithMany()
                        .HasForeignKey("personaidentificacion");

                    b.Navigation("persona");
                });
#pragma warning restore 612, 618
        }
    }
}
